[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' data: https:;
      script-src 'self' https://www.gstatic.com;
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
      connect-src 'self'
        https://firestore.googleapis.com
        https://identitytoolkit.googleapis.com
        https://securetoken.googleapis.com
        https://www.googleapis.com
        https://upload.wikimedia.org
        https://simplemaps.com;
    """
